import { add } from 'date-fns';
import { Trip } from './types';

export const TRIPS: Trip[] = [
  {
    id: '0',
    name: 'Zjawiskowa Tajlandia',
    country: 'Thailand',
    startDate: add(new Date(), { months: 2 }),
    endDate: add(new Date(), { months: 3 }),
    description: 'Discover Thailand',
    photoUrl:
      'https://www.holidify.com/images/cmsuploads/compressed/Isla_Tapu2C_Phuket2C_Tailandia2C_2013-08-202C_DD_36_20190712163859.JPG',
    price: 1000,
    seats: 60,
    rating: 6,
    category: 'zagranica',
  },
  {
    id: '1',
    name: 'Zjawiskowa Tajlandia',
    country: 'Thailand',
    startDate: add(new Date(), { months: 2 }),
    endDate: add(new Date(), { months: 3 }),
    description: 'Discover Thailand',
    photoUrl:
      'https://www.holidify.com/images/cmsuploads/compressed/Isla_Tapu2C_Phuket2C_Tailandia2C_2013-08-202C_DD_36_20190712163859.JPG',
    price: 2000,
    seats: 60,
    rating: 0,
    category: 'polska',
  },
  {
    id: '2',
    name: 'Zjawiskowa Tajlandia',
    country: 'Thailand',
    startDate: add(new Date(), { months: 2 }),
    endDate: add(new Date(), { months: 3 }),
    description: 'Discover Thailand',
    photoUrl:
      'https://www.holidify.com/images/cmsuploads/compressed/Isla_Tapu2C_Phuket2C_Tailandia2C_2013-08-202C_DD_36_20190712163859.JPG',
    price: 4000,
    seats: 60,
    rating: 0,
    category: 'zagranica',
  },
  {
    id: '3',
    name: 'Zjawiskowa Tajlandia',
    country: 'Thailand',
    startDate: add(new Date(), { months: 2 }),
    endDate: add(new Date(), { months: 3 }),
    description: 'Discover Thailand',
    photoUrl:
      'https://www.holidify.com/images/cmsuploads/compressed/Isla_Tapu2C_Phuket2C_Tailandia2C_2013-08-202C_DD_36_20190712163859.JPG',
    price: 5000,
    seats: 60,
    rating: 0,
    category: 'polska',
  },
  {
    id: '4',
    name: 'Zjawiskowa Tajlandia',
    country: 'Thailand',
    startDate: add(new Date(), { months: 2 }),
    endDate: add(new Date(), { months: 3 }),
    description: 'Discover Thailand',
    photoUrl:
      'https://www.holidify.com/images/cmsuploads/compressed/Isla_Tapu2C_Phuket2C_Tailandia2C_2013-08-202C_DD_36_20190712163859.JPG',
    price: 6000,
    seats: 60,
    rating: 0,
    category: 'zagranica',
  },
  {
    id: '5',
    name: 'Zjawiskowa Tajlandia',
    country: 'Thailand',
    startDate: add(new Date(), { months: 2 }),
    endDate: add(new Date(), { months: 3 }),
    description: 'Discover Thailand',
    photoUrl:
      'https://www.holidify.com/images/cmsuploads/compressed/Isla_Tapu2C_Phuket2C_Tailandia2C_2013-08-202C_DD_36_20190712163859.JPG',
    price: 7000,
    seats: 60,
    rating: 0,
    category: 'polska',
  },
  {
    id: '6',
    name: 'Zjawiskowa Tajlandia',
    country: 'Thailand',
    startDate: add(new Date(), { months: 2 }),
    endDate: add(new Date(), { months: 3 }),
    description: 'Discover Thailand',
    photoUrl:
      'https://www.holidify.com/images/cmsuploads/compressed/Isla_Tapu2C_Phuket2C_Tailandia2C_2013-08-202C_DD_36_20190712163859.JPG',
    price: 8000,
    seats: 60,
    rating: 0,
    category: 'polska',
  },
  {
    id: '7',
    name: 'Zjawiskowa Tajlandia',
    country: 'Thailand',
    startDate: add(new Date(), { months: 2 }),
    endDate: add(new Date(), { months: 3 }),
    description: 'Discover Thailand',
    photoUrl:
      'https://www.holidify.com/images/cmsuploads/compressed/Isla_Tapu2C_Phuket2C_Tailandia2C_2013-08-202C_DD_36_20190712163859.JPG',
    price: 3000,
    seats: 60,
    rating: 0,
    category: 'polska',
  },
];
